Adil/Controllers/StatusesDropDownController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Adil.Dal.Repository;

namespace Adil.Controllers
{
    public class StatusesDropDownController : Controller
    {
        private readonly IStatusesRepository statuses;
        public StatusesDropDownController(IStatusesRepository _statuses)
        {
            statuses = _statuses;
        }

        public ActionResult GetDropdown(int selectedId, string name)
        {
            ViewData.Model = statuses.GetAll().ToList().Select(s=>new SelectListItem
                                 {
                                     Text = s.StatusName,
                                     Value = s.Id.ToString(),
                                     Selected = (s.Id == selectedId)
                                 });
            ViewData.ModelMetadata =
                new ModelMetadata(
                    ModelMetadataProviders.Current,
                    null,
                    null,
                    typeof(int),
                    name) { NullDisplayText = " выберите статус из списка" };
            return View("Dropdown");
        }

    }
}

Adil/Views/Shared/EditorTemplates/FileUpload.cshtml
@model byte[]
@{
    if (Model == null)
    {
        <input type="file" name="Photo" />
    }
    else
    {
        string imageBase64 = Convert.ToBase64String(Model);
        string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
        <img src="@imageSrc" width="100" height="100" />
    }
}


 

Adil/Views/Shared/EditorTemplates/RPStatusDropDown.cshtml
@{ Html.RenderAction("GetDropdown", "StatusesDropDown", new { selectedId = Model ?? 0, name = "RPStatus" }); }

Adil/Views/Shared/EditorTemplates/StatusIdDropDown.cshtml
@{ Html.RenderAction("GetDropdown", "StatusesDropDown", new { selectedId = Model ?? 0, name = "StatusId" }); }